<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Raghav_Global" failures="10" tests="19" name="PetStore Tests" time="25.136" errors="0" timestamp="2025-09-16T17:35:49 IST">
  <testcase classname="api.test.DDTests" name="testCreateUserDD" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: Error initializing ExcelUtils with file: src/test/resources/TestData.xlsx">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: Error initializing ExcelUtils with file: src/test/resources/TestData.xlsx
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Error initializing ExcelUtils with file: src/test/resources/TestData.xlsx
at api.utilities.ExcelUtils.<init>(ExcelUtils.java:21)
at api.utilities.ExcelDataProviders.getUserData(ExcelDataProviders.java:11)
... 29 more
Caused by: java.io.FileNotFoundException: src\test\resources\TestData.xlsx (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.ExcelUtils.<init>(ExcelUtils.java:17)
... 37 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testCreateUserDD -->
  <testcase classname="api.test.DDTests" name="testReadUserDD" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: Error initializing ExcelUtils with file: src/test/resources/TestData.xlsx">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: Error initializing ExcelUtils with file: src/test/resources/TestData.xlsx
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Error initializing ExcelUtils with file: src/test/resources/TestData.xlsx
at api.utilities.ExcelUtils.<init>(ExcelUtils.java:21)
at api.utilities.ExcelDataProviders.getUserData(ExcelDataProviders.java:11)
... 29 more
Caused by: java.io.FileNotFoundException: src\test\resources\TestData.xlsx (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.ExcelUtils.<init>(ExcelUtils.java:17)
... 37 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testReadUserDD -->
  <testcase classname="api.test.ISATests" name="testISAEndpoints" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public void api.test.ISATests.testISAEndpoints(java.lang.String,java.lang.String,int) requires a @DataProvider named : ISAData in class api.utilities.ExcelDataProviders">
      <![CDATA[org.testng.TestNGException: 
Method public void api.test.ISATests.testISAEndpoints(java.lang.String,java.lang.String,int) requires a @DataProvider named : ISAData in class api.utilities.ExcelDataProviders
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testISAEndpoints -->
  <testcase classname="api.test.PaymentTestsISA" name="testCreatePayment" time="7.142">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.PaymentTestsISA.testCreatePayment(PaymentTestsISA.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testCreatePayment -->
  <testcase classname="api.test.PaymentTestsISA" name="testGetPayment" time="1.289">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.PaymentTestsISA.testGetPayment(PaymentTestsISA.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testGetPayment -->
  <testcase classname="api.test.PaymentTestsISA" name="testUpdatePayment" time="1.227">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.PaymentTestsISA.testUpdatePayment(PaymentTestsISA.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testUpdatePayment -->
  <testcase classname="api.test.PaymentTestsISA" name="testDeletePayment" time="1.319">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.PaymentTestsISA.testDeletePayment(PaymentTestsISA.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDeletePayment -->
  <testcase classname="api.test.UserTests" name="testCreateUser" time="1.352"/>
  <testcase classname="api.test.UserTests" name="testGetUser" time="1.398">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at api.test.UserTests.testGetUser(UserTests.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- testGetUser -->
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="1.059"/>
  <testcase classname="api.test.UserTests" name="testDeleteUser" time="1.08"/>
  <testcase classname="api.test.UserTests2" name="testCreateUser" time="1.051"/>
  <testcase classname="api.test.UserTests2" name="testGetUser" time="1.481">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at api.test.UserTests2.testGetUser(UserTests2.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- testGetUser -->
  <testcase classname="api.test.UserTests2" name="testUpdateUser" time="1.219"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUser" time="1.158"/>
  <testcase classname="api.test.UserTestsISA" name="testCreateUser" time="0.957"/>
  <testcase classname="api.test.UserTestsISA" name="testGetUser" time="1.023">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at api.test.UserTestsISA.testGetUser(UserTestsISA.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- testGetUser -->
  <testcase classname="api.test.UserTestsISA" name="testUpdateUser" time="1.009"/>
  <testcase classname="api.test.UserTestsISA" name="testDeleteUser" time="0.987"/>
</testsuite> <!-- PetStore Tests -->
